server:
  servlet:
    application-display-name: Hydra
  port: 8080

spring:
  servlet:
    multipart:
      location: ${java.io.tmpdir}
      file-size-threshold: 5MB
      max-file-size: 25MB

logging:
  level:
    inc.troll: info

hydra:
  bot-token: ${BOT_TOKEN}
  channel-id: ${BOT_CHANNEL_ID}